--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.791.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27/4/2022 16:49:44
-- Server version: 10.4.22
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE mvc;

--
-- Drop table `productos`
--
DROP TABLE IF EXISTS productos;

--
-- Set default database
--
USE mvc;

--
-- Create table `productos`
--
CREATE TABLE productos (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(255) DEFAULT NULL,
  descripcion VARCHAR(255) DEFAULT NULL,
  precio INT(11) DEFAULT NULL,
  stock INT(11) DEFAULT NULL,
  imagen VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 27,
AVG_ROW_LENGTH = 2340,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

-- 
-- Dumping data for table productos
--
INSERT INTO productos VALUES
(19, 'Remeron Amarillo', 'Remeron de mujer amarillo. ', 1500, 5, '3619yellow-5263498_1280.jpg'),
(20, 'Musculosa Blanca', 'Musculosa blanca de mujer', 700, 10, '3810fashion-4785546_1280.jpg'),
(21, 'Top negro', 'Top negro de mujer', 700, 10, '4128fashion-5328924_1280.jpg'),
(23, 'Conjunto', 'Conjunto blusa y pantalon', 3000, 10, '4506fashion-5138277_1280.jpg'),
(24, 'Conjunto', 'Conjunto violeta', 3000, 3, '5019purple-5400725_1280.jpg'),
(25, 'Pollera', 'Pollera', 2000, 5, '1033fashion-5304132_1280.jpg'),
(26, 'Cartera', 'Cartera de cuero marron', 5000, 10, '1313bag-5400665_1280.jpg');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;